sudo: false

language: node_js

node_js:
  - "8"
  - "10"

cache:
  directories:
    - node_modules

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

addons:
  sauce_connect: true

script:
  - npm run build
  - COVERAGE=true ALLOW_SAUCELABS=false npm run test
  - if [ "$TRAVIS_NODE_VERSION" = "8" ]; then
    COVERAGE=false FLAKEY=false PERFORMANCE=false ALLOW_SAUCELABS=true npm run test:karma;
    ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info;
    fi
